### ISSUE TITLE
Reading CLOB datatype converts '’' to '?' resptively. 

### ISSUE THREAD

**Issue by swayanjeet** [Bluehorn/cx_Oracle#1]
I am using cx_Oracle.LOB.read() for reading the data.
Any change of encoding also doesn't work. 
Can you please tell how to read data properly ??

**Comment by Bluehorn** [comment]
Sorry, no idea what you are talking about. I only did a small patch to upstream cx_Oracle to fix a problem with executemany that I was running into.
I do not use cx_Oracle directly but funnel all DB actions through SQLAlchemy so I even never used the LOB class.

You might have more luck looking at the resources of the upstream cx_Oracle package: http://cx-oracle.sourceforge.net/
